"""Build synthetic GuardDuty events for a controlled lab exercise.

These events are documents. They do not scan, exploit, or change a resource
until a deployed playbook receives one and containment mode is enforce.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

PLAYBOOK_FINDING_TYPES = {
    "ec2": "CryptoCurrency:EC2/BitcoinTool.B",
    "iam": "UnauthorizedAccess:IAMUser/MaliciousIPCaller.Custom",
    "s3": "Exfiltration:S3/MaliciousIPCaller",
}


def build_event(
    *,
    finding_type: str,
    severity: float,
    account_id: str,
    region: str,
    instance_id: str | None = None,
    user_name: str | None = None,
    access_key_id: str | None = None,
    user_type: str = "IAMUser",
    bucket_names: list[str] | None = None,
    finding_id: str | None = None,
) -> dict[str, Any]:
    """Return an EventBridge-shaped GuardDuty finding."""

    identifier = finding_id or f"sim-{uuid4()}"
    resource: dict[str, Any] = {"resourceType": "Unknown"}
    if instance_id:
        resource["resourceType"] = "Instance"
        resource["instanceDetails"] = {"instanceId": instance_id}
    if user_name or access_key_id:
        resource["resourceType"] = "AccessKey"
        resource["accessKeyDetails"] = {
            "accessKeyId": access_key_id or "",
            "principalId": "AIDAEXAMPLE",
            "userName": user_name or "",
            "userType": user_type,
        }
        if instance_id:
            resource["instanceDetails"] = {"instanceId": instance_id}
    if bucket_names:
        resource["resourceType"] = "S3Bucket"
        resource["s3BucketDetails"] = [
            {"name": name, "arn": f"arn:aws:s3:::{name}", "type": "Destination"} for name in bucket_names
        ]

    return {
        "version": "0",
        "id": str(uuid4()),
        "detail-type": "GuardDuty Finding",
        "source": "aws.guardduty",
        "account": account_id,
        "time": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "region": region,
        "resources": [],
        "detail": {
            "schemaVersion": "2.0",
            "accountId": account_id,
            "region": region,
            "id": identifier,
            "type": finding_type,
            "severity": severity,
            "title": finding_type,
            "description": ("Synthetic finding generated by the incident response lab. This is not an attack."),
            "resource": resource,
        },
    }
